all:
	../bin/XPP bake.lua

noart:
	../bin/XPP bake.lua noart

bump:
	../bin/XPP bake.lua bump

debug:
	../bin/XPP bake.lua debug

release:
	../bin/XPP bake.lua release

art:
	../bin/XPP makeart.lua



